In [14]:
import pandas as pd

In [15]:
df_master = pd.read_csv("Student.csv")

In [16]:
df_master.shape

(20, 10)

In [17]:
df_master.head()

,รหัสนักศึกษา,ชื่อ,อายุ,เพศ,คณะ,GPA,ส่วนสูง_cm,น้ำหนัก_kg,ชั่วโมงเรียน_ต่อสัปดาห์,วันที่ลงทะเบียน
0,64001,สมชาย,20.0,ชาย,วิทยาศาสตร์,3.21,170.0,65.0,15.0,2024-01-23
1,64002,สมหญิง,21.0,หญิง,วิทย์,3.45,165.0,58.0,20.0,2024-02-05
2,64003,NaN,NaN,Male,Science,3.67,175.0,NaN,25.0,2024-01-13
3,64004,สมศักดิ์,22.0,ช,คณะวิทยาศาสตร์,-1.00,168.0,70.0,10.0,2023-12-30
4,64005,สมใจ,19.0,ญ,วิศวะ,3.89,160.0,52.0,30.0,2024-01-27

In [18]:
print("="*50)
print("🎯 ข้อมูลหลัก (Master Dataset) ที่จะใช้ตลอดบทเรียน")
print("="*50)
print(df_master)
print("\n📊 สรุปปัญหาที่พบในข้อมูล:")
print(f"- ค่าหายทั้งหมด: {df_master.isnull().sum().sum()} ค่า")
print(f"- อายุผิดปกติ: {df_master[df_master['อายุ'] > 100]['อายุ'].values if any(df_master['อายุ'] > 100) else 'ไม่มี'}")
print(f"- GPA ผิดปกติ: {df_master[(df_master['GPA'] < 0) | (df_master['GPA'] > 4)]['GPA'].values if any((df_master['GPA'] < 0) | (df_master['GPA'] > 4)) else 'ไม่มี'}")
print(f"- รูปแบบการเขียนคณะ: {df_master['คณะ'].nunique()} แบบ")
print(f"- รูปแบบการเขียนเพศ: {df_master['เพศ'].nunique()} แบบ")

==================================================
🎯 ข้อมูลหลัก (Master Dataset) ที่จะใช้ตลอดบทเรียน
==================================================
    รหัสนักศึกษา      ชื่อ   อายุ     เพศ             คณะ   GPA  ส่วนสูง_cm  \
0          64001     สมชาย   20.0     ชาย     วิทยาศาสตร์  3.21       170.0
1          64002    สมหญิง   21.0    หญิง           วิทย์  3.45       165.0
2          64003       NaN    NaN    Male         Science  3.67       175.0
3          64004  สมศักดิ์   22.0       ช  คณะวิทยาศาสตร์ -1.00       168.0
4          64005      สมใจ   19.0       ญ           วิศวะ  3.89       160.0
5          64006     กานต์  150.0     ชาย     Engineering  3.12       172.0
6          64007     กิตติ   21.0    หญิง        วิศวกรรม  4.50       158.0
7          64008      จิรา   20.0       F      ศิลปศาสตร์  2.98       180.0
8          64009    ชนาธิป   23.0       M            Arts  3.34       163.0
9          64010      ดารา   21.0    หญิง           ศิลป์  3.56       167.0
10         64011      ธีระ    NaN     NaN             NaN  3.78         NaN
11         64012       นภา   22.0     ชาย           วิทย์   NaN       171.0
12         64013     บุญมี   20.0    หญิง           วิศวฯ  3.23       169.0
13         64014     ปรีชา   21.0     ชาย    Liberal Arts  3.45       164.0
14         64015     พิมพ์   22.0  Female             Sci  3.67       162.0
15         64016      ภูมิ   19.0       ช     วิทยาศาสตร์  3.89       173.0
16         64017      มานี   20.0       ญ  วิศวกรรมศาสตร์  3.01       166.0
17         64018      ยุพา   21.0    หญิง             NaN  3.23       161.0
18         64019     รัตนา    NaN     ชาย      ศิลปศาสตร์   NaN       174.0
19         64020     ลัดดา   22.0     NaN         Science  3.45       168.0

    น้ำหนัก_kg  ชั่วโมงเรียน_ต่อสัปดาห์ วันที่ลงทะเบียน
0         65.0                     15.0      2024-01-23
1         58.0                     20.0      2024-02-05
2          NaN                     25.0      2024-01-13
3         70.0                     10.0      2023-12-30
4         52.0                     30.0      2024-01-27
5         75.0                     12.0      2023-12-23
6         48.0                     35.0      2024-01-05
7         82.0                     18.0      2024-01-23
8         55.0                     22.0      2024-02-11
9         60.0                     28.0      2024-01-03
10        68.0                      NaN      2024-01-07
11         NaN                     16.0      2023-12-26
12        72.0                     24.0      2023-12-26
13        54.0                     19.0      2024-01-08
14        56.0                     26.0      2024-02-06
15        78.0                     14.0      2024-01-20
16        62.0                     21.0      2024-01-24
17        50.0                     27.0      2024-01-08
18        76.0                      NaN      2023-12-18
19        64.0                     23.0      2024-01-06

📊 สรุปปัญหาที่พบในข้อมูล:
- ค่าหายทั้งหมด: 15 ค่า
- อายุผิดปกติ: [150.]
- GPA ผิดปกติ: [-1.   4.5]
- รูปแบบการเขียนคณะ: 14 แบบ
- รูปแบบการเขียนเพศ: 8 แบบ

In [19]:
df_original = df_master.copy()

In [20]:
df_original

,รหัสนักศึกษา,ชื่อ,อายุ,เพศ,คณะ,GPA,ส่วนสูง_cm,น้ำหนัก_kg,ชั่วโมงเรียน_ต่อสัปดาห์,วันที่ลงทะเบียน
0,64001,สมชาย,20.0,ชาย,วิทยาศาสตร์,3.21,170.0,65.0,15.0,2024-01-23
1,64002,สมหญิง,21.0,หญิง,วิทย์,3.45,165.0,58.0,20.0,2024-02-05
2,64003,NaN,NaN,Male,Science,3.67,175.0,NaN,25.0,2024-01-13
3,64004,สมศักดิ์,22.0,ช,คณะวิทยาศาสตร์,-1.00,168.0,70.0,10.0,2023-12-30
4,64005,สมใจ,19.0,ญ,วิศวะ,3.89,160.0,52.0,30.0,2024-01-27
5,64006,กานต์,150.0,ชาย,Engineering,3.12,172.0,75.0,12.0,2023-12-23
6,64007,กิตติ,21.0,หญิง,วิศวกรรม,4.50,158.0,48.0,35.0,2024-01-05
7,64008,จิรา,20.0,F,ศิลปศาสตร์,2.98,180.0,82.0,18.0,2024-01-23
8,64009,ชนาธิป,23.0,M,Arts,3.34,163.0,55.0,22.0,2024-02-11
9,64010,ดารา,21.0,หญิง,ศิลป์,3.56,167.0,60.0,28.0,2024-01-03
10,64011,ธีระ,NaN,NaN,NaN,3.78,NaN,68.0,NaN,2024-01-07
11,64012,นภา,22.0,ชาย,วิทย์,NaN,171.0,NaN,16.0,2023-12-26
12,64013,บุญมี,20.0,หญิง,วิศวฯ,3.23,169.0,72.0,24.0,2023-12-26
13,64014,ปรีชา,21.0,ชาย,Liberal Arts,3.45,164.0,54.0,19.0,2024-01-08
14,64015,พิมพ์,22.0,Female,Sci,3.67,162.0,56.0,26.0,2024-02-06
15,64016,ภูมิ,19.0,ช,วิทยาศาสตร์,3.89,173.0,78.0,14.0,2024-01-20
16,64017,มานี,20.0,ญ,วิศวกรรมศาสตร์,3.01,166.0,62.0,21.0,2024-01-24
17,64018,ยุพา,21.0,หญิง,NaN,3.23,161.0,50.0,27.0,2024-01-08
18,64019,รัตนา,NaN,ชาย,ศิลปศาสตร์,NaN,174.0,76.0,NaN,2023-12-18
19,64020,ลัดดา,22.0,NaN,Science,3.45,168.0,64.0,23.0,2024-01-06

In [22]:
# วิเคราะห์ข้อมูล df_master ที่สร้างไว้
print("="*50)
print("📋 ข้อมูลทั่วไปของ Dataset")
print("="*50)
df_master.info()

print("\n" + "="*50)
print("📊 สถิติเชิงพรรณนา")
print("="*50)
print(df_master.describe())

# ตรวจสอบค่าหายในแต่ละคอลัมน์
missing_counts = df_master.isnull().sum()
print("\n❌ ค่าหายในแต่ละคอลัมน์:")
for col, count in missing_counts[missing_counts > 0].items():
    percentage = (count / len(df_master)) * 100
    print(f"   - {col}: {count} ค่า ({percentage:.1f}%)")

==================================================
📋 ข้อมูลทั่วไปของ Dataset
==================================================
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 10 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   รหัสนักศึกษา             20 non-null     int64
 1   ชื่อ                     19 non-null     object
 2   อายุ                     17 non-null     float64
 3   เพศ                      18 non-null     object
 4   คณะ                      18 non-null     object
 5   GPA                      18 non-null     float64
 6   ส่วนสูง_cm               19 non-null     float64
 7   น้ำหนัก_kg               18 non-null     float64
 8   ชั่วโมงเรียน_ต่อสัปดาห์  18 non-null     float64
 9   วันที่ลงทะเบียน          20 non-null     object
dtypes: float64(5), int64(1), object(4)
memory usage: 1.7+ KB

==================================================
📊 สถิติเชิงพรรณนา
==================================================
       รหัสนักศึกษา        อายุ        GPA  ส่วนสูง_cm  น้ำหนัก_kg  \
count      20.00000   17.000000  18.000000   19.000000   18.000000
mean    64010.50000   28.470588   3.246111  167.684211   63.611111
std         5.91608   31.337114   1.123326    5.706260   10.279270
min     64001.00000   19.000000  -1.000000  158.000000   48.000000
25%     64005.75000   20.000000   3.215000  163.500000   55.250000
50%     64010.50000   21.000000   3.450000  168.000000   63.000000
75%     64015.25000   22.000000   3.670000  171.500000   71.500000
max     64020.00000  150.000000   4.500000  180.000000   82.000000

       ชั่วโมงเรียน_ต่อสัปดาห์
count                18.000000
mean                 21.388889
std                   6.598920
min                  10.000000
25%                  16.500000
50%                  21.500000
75%                  25.750000
max                  35.000000

❌ ค่าหายในแต่ละคอลัมน์:
   - ชื่อ: 1 ค่า (5.0%)
   - อายุ: 3 ค่า (15.0%)
   - เพศ: 2 ค่า (10.0%)
   - คณะ: 2 ค่า (10.0%)
   - GPA: 2 ค่า (10.0%)
   - ส่วนสูง_cm: 1 ค่า (5.0%)
   - น้ำหนัก_kg: 2 ค่า (10.0%)
   - ชั่วโมงเรียน_ต่อสัปดาห์: 2 ค่า (10.0%)

In [23]:
df_clean = df_master.dropna()

In [24]:
print(f"\nผลการลบ - ก่อนลบ {len(df)} แถว, หลังลบ {len(df_clean)} แถว")
print("หลังลบ (เหลือ 9 คน):")
print(df_clean)

ผลการลบ - ก่อนลบ 20 แถว, หลังลบ 14 แถว
หลังลบ (เหลือ 9 คน):
    รหัสนักศึกษา      ชื่อ   อายุ     เพศ             คณะ   GPA  ส่วนสูง_cm  \
0          64001     สมชาย   20.0     ชาย     วิทยาศาสตร์  3.21       170.0
1          64002    สมหญิง   21.0    หญิง           วิทย์  3.45       165.0
3          64004  สมศักดิ์   22.0       ช  คณะวิทยาศาสตร์ -1.00       168.0
4          64005      สมใจ   19.0       ญ           วิศวะ  3.89       160.0
5          64006     กานต์  150.0     ชาย     Engineering  3.12       172.0
6          64007     กิตติ   21.0    หญิง        วิศวกรรม  4.50       158.0
7          64008      จิรา   20.0       F      ศิลปศาสตร์  2.98       180.0
8          64009    ชนาธิป   23.0       M            Arts  3.34       163.0
9          64010      ดารา   21.0    หญิง           ศิลป์  3.56       167.0
12         64013     บุญมี   20.0    หญิง           วิศวฯ  3.23       169.0
13         64014     ปรีชา   21.0     ชาย    Liberal Arts  3.45       164.0
14         64015     พิมพ์   22.0  Female             Sci  3.67       162.0
15         64016      ภูมิ   19.0       ช     วิทยาศาสตร์  3.89       173.0
16         64017      มานี   20.0       ญ  วิศวกรรมศาสตร์  3.01       166.0

    น้ำหนัก_kg  ชั่วโมงเรียน_ต่อสัปดาห์ วันที่ลงทะเบียน
0         65.0                     15.0      2024-01-23
1         58.0                     20.0      2024-02-05
3         70.0                     10.0      2023-12-30
4         52.0                     30.0      2024-01-27
5         75.0                     12.0      2023-12-23
6         48.0                     35.0      2024-01-05
7         82.0                     18.0      2024-01-23
8         55.0                     22.0      2024-02-11
9         60.0                     28.0      2024-01-03
12        72.0                     24.0      2023-12-26
13        54.0                     19.0      2024-01-08
14        56.0                     26.0      2024-02-06
15        78.0                     14.0      2024-01-20
16        62.0                     21.0      2024-01-24

In [25]:
df_clean

,รหัสนักศึกษา,ชื่อ,อายุ,เพศ,คณะ,GPA,ส่วนสูง_cm,น้ำหนัก_kg,ชั่วโมงเรียน_ต่อสัปดาห์,วันที่ลงทะเบียน
0,64001,สมชาย,20.0,ชาย,วิทยาศาสตร์,3.21,170.0,65.0,15.0,2024-01-23
1,64002,สมหญิง,21.0,หญิง,วิทย์,3.45,165.0,58.0,20.0,2024-02-05
3,64004,สมศักดิ์,22.0,ช,คณะวิทยาศาสตร์,-1.00,168.0,70.0,10.0,2023-12-30
4,64005,สมใจ,19.0,ญ,วิศวะ,3.89,160.0,52.0,30.0,2024-01-27
5,64006,กานต์,150.0,ชาย,Engineering,3.12,172.0,75.0,12.0,2023-12-23
6,64007,กิตติ,21.0,หญิง,วิศวกรรม,4.50,158.0,48.0,35.0,2024-01-05
7,64008,จิรา,20.0,F,ศิลปศาสตร์,2.98,180.0,82.0,18.0,2024-01-23
8,64009,ชนาธิป,23.0,M,Arts,3.34,163.0,55.0,22.0,2024-02-11
9,64010,ดารา,21.0,หญิง,ศิลป์,3.56,167.0,60.0,28.0,2024-01-03
12,64013,บุญมี,20.0,หญิง,วิศวฯ,3.23,169.0,72.0,24.0,2023-12-26
13,64014,ปรีชา,21.0,ชาย,Liberal Arts,3.45,164.0,54.0,19.0,2024-01-08
14,64015,พิมพ์,22.0,Female,Sci,3.67,162.0,56.0,26.0,2024-02-06
15,64016,ภูมิ,19.0,ช,วิทยาศาสตร์,3.89,173.0,78.0,14.0,2024-01-20
16,64017,มานี,20.0,ญ,วิศวกรรมศาสตร์,3.01,166.0,62.0,21.0,2024-01-24

In [28]:
mean_age = df_master['อายุ'].mean()
df_master['อายุ'] = df_master['อายุ'].fillna(mean_age)

In [29]:
print(f"\nค่าเฉลี่ยอายุ - {mean_age:.1f} ปี")
print("หลังเติมค่า")
print(df)

ค่าเฉลี่ยอายุ - 28.5 ปี
หลังเติมค่า
    รหัสนักศึกษา      ชื่อ   อายุ     เพศ             คณะ   GPA  ส่วนสูง_cm  \
0          64001     สมชาย   20.0     ชาย     วิทยาศาสตร์  3.21       170.0
1          64002    สมหญิง   21.0    หญิง           วิทย์  3.45       165.0
2          64003       NaN    NaN    Male         Science  3.67       175.0
3          64004  สมศักดิ์   22.0       ช  คณะวิทยาศาสตร์ -1.00       168.0
4          64005      สมใจ   19.0       ญ           วิศวะ  3.89       160.0
5          64006     กานต์  150.0     ชาย     Engineering  3.12       172.0
6          64007     กิตติ   21.0    หญิง        วิศวกรรม  4.50       158.0
7          64008      จิรา   20.0       F      ศิลปศาสตร์  2.98       180.0
8          64009    ชนาธิป   23.0       M            Arts  3.34       163.0
9          64010      ดารา   21.0    หญิง           ศิลป์  3.56       167.0
10         64011      ธีระ    NaN     NaN             NaN  3.78         NaN
11         64012       นภา   22.0     ชาย           วิทย์   NaN       171.0
12         64013     บุญมี   20.0    หญิง           วิศวฯ  3.23       169.0
13         64014     ปรีชา   21.0     ชาย    Liberal Arts  3.45       164.0
14         64015     พิมพ์   22.0  Female             Sci  3.67       162.0
15         64016      ภูมิ   19.0       ช     วิทยาศาสตร์  3.89       173.0
16         64017      มานี   20.0       ญ  วิศวกรรมศาสตร์  3.01       166.0
17         64018      ยุพา   21.0    หญิง             NaN  3.23       161.0
18         64019     รัตนา    NaN     ชาย      ศิลปศาสตร์   NaN       174.0
19         64020     ลัดดา   22.0     NaN         Science  3.45       168.0

    น้ำหนัก_kg  ชั่วโมงเรียน_ต่อสัปดาห์ วันที่ลงทะเบียน
0         65.0                     15.0      2024-01-23
1         58.0                     20.0      2024-02-05
2          NaN                     25.0      2024-01-13
3         70.0                     10.0      2023-12-30
4         52.0                     30.0      2024-01-27
5         75.0                     12.0      2023-12-23
6         48.0                     35.0      2024-01-05
7         82.0                     18.0      2024-01-23
8         55.0                     22.0      2024-02-11
9         60.0                     28.0      2024-01-03
10        68.0                      NaN      2024-01-07
11         NaN                     16.0      2023-12-26
12        72.0                     24.0      2023-12-26
13        54.0                     19.0      2024-01-08
14        56.0                     26.0      2024-02-06
15        78.0                     14.0      2024-01-20
16        62.0                     21.0      2024-01-24
17        50.0                     27.0      2024-01-08
18        76.0                      NaN      2023-12-18
19        64.0                     23.0      2024-01-06

In [30]:
mean_age

np.float64(28.470588235294123)

In [32]:
d_use = df_master['คณะ']
df_master['คณะ'].fillna(d_use.mode()[0], inplace=True)

In [33]:
print("\nหลังเติมค่า")
print(df_master)

หลังเติมค่า
    รหัสนักศึกษา      ชื่อ        อายุ     เพศ             คณะ   GPA  \
0          64001     สมชาย   20.000000     ชาย     วิทยาศาสตร์  3.21
1          64002    สมหญิง   21.000000    หญิง           วิทย์  3.45
2          64003       NaN   28.470588    Male         Science  3.67
3          64004  สมศักดิ์   22.000000       ช  คณะวิทยาศาสตร์ -1.00
4          64005      สมใจ   19.000000       ญ           วิศวะ  3.89
5          64006     กานต์  150.000000     ชาย     Engineering  3.12
6          64007     กิตติ   21.000000    หญิง        วิศวกรรม  4.50
7          64008      จิรา   20.000000       F      ศิลปศาสตร์  2.98
8          64009    ชนาธิป   23.000000       M            Arts  3.34
9          64010      ดารา   21.000000    หญิง           ศิลป์  3.56
10         64011      ธีระ   28.470588     NaN         Science  3.78
11         64012       นภา   22.000000     ชาย           วิทย์   NaN
12         64013     บุญมี   20.000000    หญิง           วิศวฯ  3.23
13         64014     ปรีชา   21.000000     ชาย    Liberal Arts  3.45
14         64015     พิมพ์   22.000000  Female             Sci  3.67
15         64016      ภูมิ   19.000000       ช     วิทยาศาสตร์  3.89
16         64017      มานี   20.000000       ญ  วิศวกรรมศาสตร์  3.01
17         64018      ยุพา   21.000000    หญิง         Science  3.23
18         64019     รัตนา   28.470588     ชาย      ศิลปศาสตร์   NaN
19         64020     ลัดดา   22.000000     NaN         Science  3.45

    ส่วนสูง_cm  น้ำหนัก_kg  ชั่วโมงเรียน_ต่อสัปดาห์ วันที่ลงทะเบียน
0        170.0        65.0                     15.0      2024-01-23
1        165.0        58.0                     20.0      2024-02-05
2        175.0         NaN                     25.0      2024-01-13
3        168.0        70.0                     10.0      2023-12-30
4        160.0        52.0                     30.0      2024-01-27
5        172.0        75.0                     12.0      2023-12-23
6        158.0        48.0                     35.0      2024-01-05
7        180.0        82.0                     18.0      2024-01-23
8        163.0        55.0                     22.0      2024-02-11
9        167.0        60.0                     28.0      2024-01-03
10         NaN        68.0                      NaN      2024-01-07
11       171.0         NaN                     16.0      2023-12-26
12       169.0        72.0                     24.0      2023-12-26
13       164.0        54.0                     19.0      2024-01-08
14       162.0        56.0                     26.0      2024-02-06
15       173.0        78.0                     14.0      2024-01-20
16       166.0        62.0                     21.0      2024-01-24
17       161.0        50.0                     27.0      2024-01-08
18       174.0        76.0                      NaN      2023-12-18
19       168.0        64.0                     23.0      2024-01-06

In [34]:
def standardize_faculty(name):
    if name in ['วิทยาศาสตร์', 'วิทย์', 'Science', 'คณะวิทยาศาสตร์']:
        return 'วิทยาศาสตร์'
    elif name in ['ศิลปศาสตร์', 'ศิลป์', 'Arts']:
        return 'ศิลปศาสตร์'
    else:
        return name

In [35]:
df_master['คณะ_มาตรฐาน'] = df_master['คณะ'].apply(standardize_faculty)

In [36]:
df_master

,รหัสนักศึกษา,ชื่อ,อายุ,เพศ,คณะ,GPA,ส่วนสูง_cm,น้ำหนัก_kg,ชั่วโมงเรียน_ต่อสัปดาห์,วันที่ลงทะเบียน,คณะ_มาตรฐาน
0,64001,สมชาย,20.000000,ชาย,วิทยาศาสตร์,3.21,170.0,65.0,15.0,2024-01-23,วิทยาศาสตร์
1,64002,สมหญิง,21.000000,หญิง,วิทย์,3.45,165.0,58.0,20.0,2024-02-05,วิทยาศาสตร์
2,64003,NaN,28.470588,Male,Science,3.67,175.0,NaN,25.0,2024-01-13,วิทยาศาสตร์
3,64004,สมศักดิ์,22.000000,ช,คณะวิทยาศาสตร์,-1.00,168.0,70.0,10.0,2023-12-30,วิทยาศาสตร์
4,64005,สมใจ,19.000000,ญ,วิศวะ,3.89,160.0,52.0,30.0,2024-01-27,วิศวะ
5,64006,กานต์,150.000000,ชาย,Engineering,3.12,172.0,75.0,12.0,2023-12-23,Engineering
6,64007,กิตติ,21.000000,หญิง,วิศวกรรม,4.50,158.0,48.0,35.0,2024-01-05,วิศวกรรม
7,64008,จิรา,20.000000,F,ศิลปศาสตร์,2.98,180.0,82.0,18.0,2024-01-23,ศิลปศาสตร์
8,64009,ชนาธิป,23.000000,M,Arts,3.34,163.0,55.0,22.0,2024-02-11,ศิลปศาสตร์
9,64010,ดารา,21.000000,หญิง,ศิลป์,3.56,167.0,60.0,28.0,2024-01-03,ศิลปศาสตร์
10,64011,ธีระ,28.470588,NaN,Science,3.78,NaN,68.0,NaN,2024-01-07,วิทยาศาสตร์
11,64012,นภา,22.000000,ชาย,วิทย์,NaN,171.0,NaN,16.0,2023-12-26,วิทยาศาสตร์
12,64013,บุญมี,20.000000,หญิง,วิศวฯ,3.23,169.0,72.0,24.0,2023-12-26,วิศวฯ
13,64014,ปรีชา,21.000000,ชาย,Liberal Arts,3.45,164.0,54.0,19.0,2024-01-08,Liberal Arts
14,64015,พิมพ์,22.000000,Female,Sci,3.67,162.0,56.0,26.0,2024-02-06,Sci
15,64016,ภูมิ,19.000000,ช,วิทยาศาสตร์,3.89,173.0,78.0,14.0,2024-01-20,วิทยาศาสตร์
16,64017,มานี,20.000000,ญ,วิศวกรรมศาสตร์,3.01,166.0,62.0,21.0,2024-01-24,วิศวกรรมศาสตร์
17,64018,ยุพา,21.000000,หญิง,Science,3.23,161.0,50.0,27.0,2024-01-08,วิทยาศาสตร์
18,64019,รัตนา,28.470588,ชาย,ศิลปศาสตร์,NaN,174.0,76.0,NaN,2023-12-18,ศิลปศาสตร์
19,64020,ลัดดา,22.000000,NaN,Science,3.45,168.0,64.0,23.0,2024-01-06,วิทยาศาสตร์

In [37]:
Q1 = df_master['อายุ'].quantile(0.25)
Q3 = df_master['อายุ'].quantile(0.75)
IQR = Q3 - Q1

In [38]:
lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

In [39]:
df_no_outliers = df_master[(df_master['อายุ'] >= lower_bound) & (df_master['อายุ'] <= upper_bound)]

In [40]:
print(f"\nขอบเขตล่าง - {lower_bound}")
print(f"ขอบเขตบน - {upper_bound}")
print(f"\nข้อมูลหลังกรองค่าผิดปกติ")
print(df_no_outliers)
print(f"\nค่าเฉลี่ยอายุ (หลังกรองค่าผิดปกติ) - {df_no_outliers['อายุ'].mean():.2f}")

ขอบเขตล่าง - 16.625
ขอบเขตบน - 25.625

ข้อมูลหลังกรองค่าผิดปกติ
    รหัสนักศึกษา      ชื่อ  อายุ     เพศ             คณะ   GPA  ส่วนสูง_cm  \
0          64001     สมชาย  20.0     ชาย     วิทยาศาสตร์  3.21       170.0
1          64002    สมหญิง  21.0    หญิง           วิทย์  3.45       165.0
3          64004  สมศักดิ์  22.0       ช  คณะวิทยาศาสตร์ -1.00       168.0
4          64005      สมใจ  19.0       ญ           วิศวะ  3.89       160.0
6          64007     กิตติ  21.0    หญิง        วิศวกรรม  4.50       158.0
7          64008      จิรา  20.0       F      ศิลปศาสตร์  2.98       180.0
8          64009    ชนาธิป  23.0       M            Arts  3.34       163.0
9          64010      ดารา  21.0    หญิง           ศิลป์  3.56       167.0
11         64012       นภา  22.0     ชาย           วิทย์   NaN       171.0
12         64013     บุญมี  20.0    หญิง           วิศวฯ  3.23       169.0
13         64014     ปรีชา  21.0     ชาย    Liberal Arts  3.45       164.0
14         64015     พิมพ์  22.0  Female             Sci  3.67       162.0
15         64016      ภูมิ  19.0       ช     วิทยาศาสตร์  3.89       173.0
16         64017      มานี  20.0       ญ  วิศวกรรมศาสตร์  3.01       166.0
17         64018      ยุพา  21.0    หญิง         Science  3.23       161.0
19         64020     ลัดดา  22.0     NaN         Science  3.45       168.0

    น้ำหนัก_kg  ชั่วโมงเรียน_ต่อสัปดาห์ วันที่ลงทะเบียน     คณะ_มาตรฐาน
0         65.0                     15.0      2024-01-23     วิทยาศาสตร์
1         58.0                     20.0      2024-02-05     วิทยาศาสตร์
3         70.0                     10.0      2023-12-30     วิทยาศาสตร์
4         52.0                     30.0      2024-01-27           วิศวะ
6         48.0                     35.0      2024-01-05        วิศวกรรม
7         82.0                     18.0      2024-01-23      ศิลปศาสตร์
8         55.0                     22.0      2024-02-11      ศิลปศาสตร์
9         60.0                     28.0      2024-01-03      ศิลปศาสตร์
11         NaN                     16.0      2023-12-26     วิทยาศาสตร์
12        72.0                     24.0      2023-12-26           วิศวฯ
13        54.0                     19.0      2024-01-08    Liberal Arts
14        56.0                     26.0      2024-02-06             Sci
15        78.0                     14.0      2024-01-20     วิทยาศาสตร์
16        62.0                     21.0      2024-01-24  วิศวกรรมศาสตร์
17        50.0                     27.0      2024-01-08     วิทยาศาสตร์
19        64.0                     23.0      2024-01-06     วิทยาศาสตร์

ค่าเฉลี่ยอายุ (หลังกรองค่าผิดปกติ) - 20.88

In [41]:
Q1, Q3

(np.float64(20.0), np.float64(22.25))

In [44]:
df_master['BMI'] = df_master['น้ำหนัก_kg'] / (df_master['ส่วนสูง_cm']/100)**2
df_master['สุขภาพ'] = pd.cut(df_master['BMI'],
                                   bins=[0, 18.5, 25, 30, 100],
                                   labels=['ผอม', 'ปกติ', 'อ้วน', 'อ้วนมาก'])

In [45]:
print(df_master[['ชื่อ', 'BMI', 'สุขภาพ']])

        ชื่อ        BMI สุขภาพ
0      สมชาย  22.491349   ปกติ
1     สมหญิง  21.303949   ปกติ
2        NaN        NaN    NaN
3   สมศักดิ์  24.801587   ปกติ
4       สมใจ  20.312500   ปกติ
5      กานต์  25.351541   อ้วน
6      กิตติ  19.227688   ปกติ
7       จิรา  25.308642   อ้วน
8     ชนาธิป  20.700817   ปกติ
9       ดารา  21.513859   ปกติ
10      ธีระ        NaN    NaN
11       นภา        NaN    NaN
12     บุญมี  25.209201   อ้วน
13     ปรีชา  20.077335   ปกติ
14     พิมพ์  21.338211   ปกติ
15      ภูมิ  26.061679   อ้วน
16      มานี  22.499637   ปกติ
17      ยุพา  19.289379   ปกติ
18     รัตนา  25.102391   อ้วน
19     ลัดดา  22.675737   ปกติ

In [46]:
faculty_mapping = {
    'วิทย์': 'วิทยาศาสตร์',
    'วิทยาศาสตร์': 'วิทยาศาสตร์',
    'ศิลปศาสตร์': 'ศิลปศาสตร์',
    'Arts': 'ศิลปศาสตร์',
    'วิศวะ': 'วิศวกรรมศาสตร์'
}

In [47]:
df_master['คณะ'] = df_master['คณะ'].map(faculty_mapping)

In [48]:
df_master

,รหัสนักศึกษา,ชื่อ,อายุ,เพศ,คณะ,GPA,ส่วนสูง_cm,น้ำหนัก_kg,ชั่วโมงเรียน_ต่อสัปดาห์,วันที่ลงทะเบียน,คณะ_มาตรฐาน,BMI,สุขภาพ
0,64001,สมชาย,20.000000,ชาย,วิทยาศาสตร์,3.21,170.0,65.0,15.0,2024-01-23,วิทยาศาสตร์,22.491349,ปกติ
1,64002,สมหญิง,21.000000,หญิง,วิทยาศาสตร์,3.45,165.0,58.0,20.0,2024-02-05,วิทยาศาสตร์,21.303949,ปกติ
2,64003,NaN,28.470588,Male,NaN,3.67,175.0,NaN,25.0,2024-01-13,วิทยาศาสตร์,NaN,NaN
3,64004,สมศักดิ์,22.000000,ช,NaN,-1.00,168.0,70.0,10.0,2023-12-30,วิทยาศาสตร์,24.801587,ปกติ
4,64005,สมใจ,19.000000,ญ,วิศวกรรมศาสตร์,3.89,160.0,52.0,30.0,2024-01-27,วิศวะ,20.312500,ปกติ
5,64006,กานต์,150.000000,ชาย,NaN,3.12,172.0,75.0,12.0,2023-12-23,Engineering,25.351541,อ้วน
6,64007,กิตติ,21.000000,หญิง,NaN,4.50,158.0,48.0,35.0,2024-01-05,วิศวกรรม,19.227688,ปกติ
7,64008,จิรา,20.000000,F,ศิลปศาสตร์,2.98,180.0,82.0,18.0,2024-01-23,ศิลปศาสตร์,25.308642,อ้วน
8,64009,ชนาธิป,23.000000,M,ศิลปศาสตร์,3.34,163.0,55.0,22.0,2024-02-11,ศิลปศาสตร์,20.700817,ปกติ
9,64010,ดารา,21.000000,หญิง,NaN,3.56,167.0,60.0,28.0,2024-01-03,ศิลปศาสตร์,21.513859,ปกติ
10,64011,ธีระ,28.470588,NaN,NaN,3.78,NaN,68.0,NaN,2024-01-07,วิทยาศาสตร์,NaN,NaN
11,64012,นภา,22.000000,ชาย,วิทยาศาสตร์,NaN,171.0,NaN,16.0,2023-12-26,วิทยาศาสตร์,NaN,NaN
12,64013,บุญมี,20.000000,หญิง,NaN,3.23,169.0,72.0,24.0,2023-12-26,วิศวฯ,25.209201,อ้วน
13,64014,ปรีชา,21.000000,ชาย,NaN,3.45,164.0,54.0,19.0,2024-01-08,Liberal Arts,20.077335,ปกติ
14,64015,พิมพ์,22.000000,Female,NaN,3.67,162.0,56.0,26.0,2024-02-06,Sci,21.338211,ปกติ
15,64016,ภูมิ,19.000000,ช,วิทยาศาสตร์,3.89,173.0,78.0,14.0,2024-01-20,วิทยาศาสตร์,26.061679,อ้วน
16,64017,มานี,20.000000,ญ,NaN,3.01,166.0,62.0,21.0,2024-01-24,วิศวกรรมศาสตร์,22.499637,ปกติ
17,64018,ยุพา,21.000000,หญิง,NaN,3.23,161.0,50.0,27.0,2024-01-08,วิทยาศาสตร์,19.289379,ปกติ
18,64019,รัตนา,28.470588,ชาย,ศิลปศาสตร์,NaN,174.0,76.0,NaN,2023-12-18,ศิลปศาสตร์,25.102391,อ้วน
19,64020,ลัดดา,22.000000,NaN,NaN,3.45,168.0,64.0,23.0,2024-01-06,วิทยาศาสตร์,22.675737,ปกติ

In [ ]:
df_master.to_csv("Student.csv", encoding = "utf-8", index = False)